portfolio mobile version skeleton
alexisuwimana/Portfolio pull request #1
Opened 2021-10-20 20:36 UTC by alexisuwimana

adding files  to the project mobile version skeleton

2021-10-20 21:44 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @alexisuwimana,

Good job so far!
Your design is next to perfect ✔️
Nice README ✔️
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-20 21:44 UTC, TedLivist commented on README.md
> +# portfolio project
- [ ] It would be better to Capitalize each word in the Project title since this is a header. For example: **Portfolio Project**

2021-10-20 21:44 UTC, TedLivist commented on README.md
> +![screenshot](./images/screenshot/screenshot-mobile-version.png)
- [ ] It would be nice to only have the working version of the project as a screenshot rather than showing the source code as that is unnecessary.

2021-10-20 21:44 UTC, TedLivist commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [ ] You can remove the 'No framwork used in this project' text as there is no need to mention it here.

- [ ] Your demo link is not working properly. You can set up the live link like this:
- Go to this link (https://github.com/alexisuwimana/Portfolio-mobile-version-skeleton/settings/pages).
- Select the branch name
- Select `root`
- Click the `Save` button

Your project will be deployed by Github Pages

2021-10-20 21:44 UTC, TedLivist commented on README.md
> +**to start you need t create a repository and clone it to your local computer**
- [ ] Please correct your typo error here.

- [ ] You are not using the proper commit message rules. Going forward, please ensure that your commit messages are **imperative** and **capitalized**. They should also be short, if possible. For example:
  - **adding files to the mobile portfolio** should have been **Add files to the mobile portfolio**
  - **adding correction from linters error to styles.css file , image, Readme correction of image logation** should have been **Add correction from linters error to styles.css file, image, Readme correction of image location**

2021-10-20 21:44 UTC, TedLivist commented on index.html
> +        <nav class="">
- [ ] Since the class attribute here is blank you can delete it as it ensures a much neater code

2021-10-20 21:44 UTC, TedLivist commented on index.html
> +        </ul>
- [ ] It appears there are unnecessary anchor tags in your header. Please remove them or use them if you intended them for something.

2021-10-20 21:44 UTC, TedLivist commented on index.html
> +        <div class="content">
- [ ] Please ensure that you align your headline item correctly. Look at the image below. The rectangular boxes indicate spaces should be covered.

![alexis](https://user-images.githubusercontent.com/36542986/138174966-54643f91-669d-4409-9f3e-c4ec0847ad1e.jpg)

2021-10-20 21:44 UTC, TedLivist commented on index.html
> +            <ul class="">
- [ ] I would suggest removing the class attribute here since it is blank and you did not use it.

2021-10-20 21:44 UTC, TedLivist commented on index.html
> +        </div>
- [ ] In keeping with [HTML and CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) please fix your indentation as it makes your code neater.

2021-10-20 21:44 UTC, TedLivist commented on index.html
> +
- [ ] Please remove unnecessary blank spaces as described by the HTML and CSS best practices

2021-10-20 21:44 UTC, TedLivist commented on styles.css
> +}
- [ ] Please ensure that the content of your header section is displayed with flexbox

2021-10-20 23:47 UTC, carlos-ssh approved these changes
Hi @alexisuwimana , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-20 23:54 UTC, merged

2021-10-30 22:37 UTC, alexisuwimana reviewed
Congratulations you did a great job so far but there is a small change you can work on just you can changes the font-family