Contact me pair programming
alexisuwimana/Portfolio pull request #3
Opened 2021-10-26 17:23 UTC by alexisuwimana

Add a contact form on the project

2021-10-26 18:41 UTC, rotimiazeez requested changes
Hi @alexisuwimana😊, 
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)
### Good job so far!❤💯
- Good clean code.✔
- Good commit messages. ✔

There are some issues that you still need to work on to go to the next project but you are almost there!🚀🎉

### Just a few changes and you are Unstoppable 🚅🚀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-26 18:41 UTC, rotimiazeez commented on index.html
> +    </section>
- [ ] Kindly know that you are implored to stick to the design as much as possible (e.g., font, colours, images, tests, margins) using the [templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471).👀😊
- FIGMA DESIGN
![screenshot (8)](https://user-images.githubusercontent.com/44624138/138938854-490d27f7-b2d7-4767-a9eb-23006686e32f.png)
- YOUR DESIGN
![screenshot (9)](https://user-images.githubusercontent.com/44624138/138938887-a732d18e-c90e-48e6-a86b-40146566ef90.png)

2021-10-26 18:41 UTC, rotimiazeez commented on index.html
> +    </section>
- [OPTIONAL] Kindly place your hamburger menu on the right side of your page instead of the middle to improve the UI(User Interface).😉

2021-10-27 21:12 UTC, fernandorpm requested changes
# :warning: Changes Required on this Pull Request! :warning:
Hello there!

You are almost there! Great work implementing the requested changes, now there's just some tiny :pinching_hand: adjustments that I would like you to change for us!

<img src="https://i.imgur.com/vfjSVsr.gif" width="300px" />

- You have done a wonderful job on this project! To highlight:
  - you have demonstrated great skills in following the template :heavy_check_mark: 
  - you have paid attention to almost all of the details :heavy_check_mark: 
  - you have written a nice and clean code :heavy_check_mark: 
  - your PR is on point :ok_hand: :heavy_check_mark: 

## Required
> These changes HAVE TO be completed in order for your project to be approved. This means that the project doesn't attend to Microverse's Standard yet. I know that it can be frustrating, but they should be seen as part of your path to become an even better Developer!

- Check the comments under review marked with the tag **[REQUIRED CHANGES]**.

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Just keep in mind that Microverse has a standard for the project requirements, to guarantee that you will be able to become a great developer, and both you and I have to follow them!
___

## Optional
> These changes are NOT mandatory. But if you want to sky-rocket :rocket: your skills and your projects, go for it! :sunglasses:

- Check the comments below marked with the tag **[OPTIONAL]**.

___
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

Cheers and Happy Coding! :heart:

> *As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).*

2021-10-27 21:12 UTC, fernandorpm commented on index.html
> +    </section>
- [ ] **[REQUIRED CHANGES]** Hello Alexis! I can see that you've been trying to implement the requested changes, but as of right now, they're still fairly different 😞 .

What I would suggest you is the following:
```css
input {
  border: 0;
  border-bottom: 2px solid lightgray;
}

textarea {
  border: 0;
  background-color: whitesmoke;
}
```

2021-10-27 22:06 UTC, rotimiazeez approved these changes
# Hi team ✌, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Kindly implement the optional changes below to improve your User-Interface😉😎.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-27 22:06 UTC, rotimiazeez commented on index.html
> +                <textarea name="contact" id="text-msg" placeholder="Enter text here" maxlength="500" required></textarea>
- [OPTIONAL] kindly add rows and cols to increase the `Textarea` to match the Figma template design.✌

2021-10-27 22:06 UTC, rotimiazeez commented on index.html
> +                    <li><a href="#"><i class="fab fa-medium-m"><img class="social-M" src="images/social/M-Disabled.png" alt="M"></i></a></li>
- [OPTIONAL] Please make sure the icon colour matches the one on your preferred design😉😊.

2021-10-27 22:11 UTC, merged